experiment_name: credit_scoring/all_models
random_state: 111

corpora:
  train: data/GiveMeSomeCredit-training.csv
  test: data/GiveMeSomeCredit-testing.csv

splitter: "core.splitters.KFoldSplitter"
splitter_params:
  shuffle: true
  random_state: 42
  n_splits: 5

classificators:
  class_path: "classifiers.LogisticRegressionClassifier"
  params:
    random_state: 42


metrics: [ "f1", "precision", "recall", "accuracy","auc" ]
